### ISSUE TITLE
test/rsa_genpkey_x509_cmp.sh is faulty

### ISSUE THREAD

**Issue by levitte** [tpm2-software/tpm2-openssl#20]
Unfortunately, I cannot say exactly how, I don't know much about CMP or CRMF.

I found this out by taking a copy of rsa_genpkey_x509_cmp.sh and removing all `-provider` and `-propquery` options with their values.

Attached edited rsa_genpkey_x509_cmp.sh and the logfile from a run.

[rsa_genpkey_x509_cmp.sh.txt](https://github.com/tpm2-software/tpm2-openssl/files/6782395/rsa_genpkey_x509_cmp.sh.txt)
[rsa_genpkey_x509_cmp.log](https://github.com/tpm2-software/tpm2-openssl/files/6782443/rsa_genpkey_x509_cmp.log)

**Comment by levitte** [comment]
This means that this script cannot succeed with the TPM2 provider either

**Comment by gotthardp** [comment]
But it used to work, grrrrr. I will have a look, but I am not an expert either.
