### ISSUE TITLE
Could tpm.a be loaded as a provider by openssl 3.0?

### ISSUE THREAD

**Issue by danielcongxu** [tpm2-software/tpm2-openssl#25]
Hello,

I see the built artifact is tpm.so by default, which indicates a shared object. And openssl is able to find it if it's installed to MODULESDIR. I wonder if's feasible to make it built into .a (aka. tpm.a), and make it recognizable as well as loadable by openssl?

**Comment by gotthardp** [comment]
Hello. The loadable openssl modules are expected to be "shared objects", i.e. `.so` files.

**Comment by danielcongxu** [comment]
Thanks!

**Comment by danielcongxu** [comment]
Hi @gotthardp 

Sorry for bothering you again. Is there a C example that instructs how to generate a CSR using tpm2-openssl?
