### ISSUE TITLE
Request for CSR generation examples using C API

### ISSUE THREAD

**Issue by danielcongxu** [tpm2-software/tpm2-openssl#26]
Hi,

Could you add a C API that instructs the way of CSR generation using TPM provider even though there's an existing one in openssl executable?

**Comment by gotthardp** [comment]
Yeah, I may add one or two C examples, but the code is exactly the same as for generating a "standard" CSR, except you have to load the provides first.
The code for a standard CSR is e.g. here: https://stackoverflow.com/questions/38949576/how-to-programmatically-create-a-certificate-signing-request-csr

**Comment by danielcongxu** [comment]
In detail, if I already obtained an AK handle after createak gets called, what's the proper way to generate csr with such an AK handle using openssl API. [The example](https://stackoverflow.com/questions/38949576/how-to-programmatically-create-a-certificate-signing-request-csr) is about private key outside of TPM

**Comment by danielcongxu** [comment]
@gotthardp 

In detail, if I already obtained an AK handle after createak gets called, what's the proper way to generate csr with such an AK handle using openssl API. [The example](https://stackoverflow.com/questions/38949576/how-to-programmatically-create-a-certificate-signing-request-csr) is about private key outside of TPM

**Comment by danielcongxu** [comment]
@gotthardp 

Thank you! Then the property order to generate csr would be as the following:

1. OSSL_PROVIDER_load the tpm2 provider
2. PEM_read_PrivateKey(handle:<handle to tpm key>, NULL, NULL, NULL) to construct a EVP_PKEY object
3. X509_REQ_set functions to set previous EVP_PKEY object, DN and etc., which fills the certificate related fields.
4. X509_REQ_sign to generate the ultimate csr.

Is that correct?

**Comment by gotthardp** [comment]
Yes, this looks good to me.

**Comment by danielcongxu** [comment]
> Yes, this looks good to me.

Sincere appreciation, have a nice day:)

**Comment by gotthardp** [comment]
If it doesn't work as expected, just let me know.

I will keep this issue open until I write some more C examples.

**Comment by danielcongxu** [comment]
Sure, I will.

**Comment by danielcongxu** [comment]
@gotthardp 

From your proposal, I had a line of "FILE *fp = fopen("handle:0x81110003", "r");" where 0x81110003 is an existing key handle retrieved from "tpm2_getcap handles-persistent".

Out of expectation, the fp results in a NULL pointer. Could you help to confirm it's the proper way to load key into EVP_PKEY object?

**Comment by gotthardp** [comment]
Oops, sorry. You cannot use the standard `fopen`. Please try https://www.openssl.org/docs/man3.0/man7/ossl_store.html instead. There is an example at the end of that page for `CERT`, but there are similar functions for a `PKEY` too.

**Comment by danielcongxu** [comment]
@gotthardp 

Oh, I see. It uses a while loop to consistently output he data read from the store. But if I tried with OSSL_STORE_INFO_get0_PKEY and return a EVP_PKEY object, do I still need the while loop? If so, how do I get the ultimate EVP_PKEY object considering the temporary EVP_PKEY object inside each iteration?

**Comment by danielcongxu** [comment]
> Oops, sorry. You cannot use the standard `fopen`. Please try https://www.openssl.org/docs/man3.0/man7/ossl_store.html instead. There is an example at the end of that page for `CERT`, but there are similar functions for a `PKEY` too.

I remote the while loop since from my purpose is to get the exact one key, and that seems to succeed.

**Comment by gotthardp** [comment]
The `OSSL_STORE_INFO_get0_PKEY` returns a pointer to an openssl internal object, while `OSSL_STORE_INFO_get1_PKEY` returns a pointer to a duplicate object. You may definitely take the duplicate object and exit the while loop.

**Comment by danielcongxu** [comment]
@gotthardp 

So the EVP_PKEY loading code should looks as follows:

EVP_PKEY *pub_key  = NULL;
while (!OSSL_STORE_eof(ctx)) {
     OSSL_STORE_INFO *info = OSSL_STORE_load(ctx);

     PEM_write_bio_PrivateKey(pub_key, OSSL_STORE_INFO_get0_PKEY(info));
     pub_key = OSSL_STORE_INFO_get1_PKEY(info);
     break;
}

Does it follow the expectation?

**Comment by gotthardp** [comment]
Plus on the beginning:
```
OSSL_STORE_CTX *ctx = OSSL_STORE_open("handle:0x81110003");
```
and at the end
```
OSSL_STORE_close(ctx);
```
plus you should probably handle the errors, i.e. call `break` only when the PKEY is successfully loaded.

**Comment by danielcongxu** [comment]
Thanks!

**Comment by danielcongxu** [comment]
Hi @gotthardp,

I was getting to programmatically to generate csr using tpm2-openssl. Now I'm getting error from OSSL_STORE_load, and from the stack the culprit seems to be this line of code: https://github.com/openssl/openssl/blob/89cd17a031e022211684eb7eb41190cf1910f9fa/crypto/store/store_result.c#L209

The provider retrieved from keymgmt is not the one loaded from OSSL_STORE_LOAD. Since the key used for signing CSR creates before OSSL_STORE_LOAD, does it mean I have to follow such an order, aka OSSL_STORE_LOAD ==> Generate TPM key ==> Generate CSR with OpenSSL?

Also I've tested against the mentioned order, and the application failed on key generation, specifically tpm2_createprimary.

Look forward to your insignts, thank you

**Comment by danielcongxu** [comment]
Here's my code snippet:

if ((ctx = OSSL_STORE_open(tpm_key_path.c_str(), nullptr, nullptr, nullptr, nullptr)) == nullptr) {
    goto CLEANUP;
}

while (!OSSL_STORE_eof(ctx)) {
    if ((info = OSSL_STORE_load(ctx)) == nullptr) {
        goto CLEANUP;
    }
    if ((p_key = OSSL_STORE_INFO_get1_PKEY(info)) == nullptr) {
        goto CLEANUP;
    }
    // Only break on key gets loaded successfully
    break;
}

**Comment by tomoveu** [comment]
@gotthardp I raised a new issue related to this functionality - I am able to perform TPM signature using EVP_DigestSign but X509_req_sign fails. 0 bytes are generated by X509_req_sign when using OSSL_STORE_open and PKEY referencing a TPM key
