### ISSUE TITLE
NULL Pointer Dereference

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-openssl#30]
in the tpm2-pkcs11 engine code that I am porting to openssl 3, I have the following:
```bash
openssl dgst -provider tpm2 -provider base -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -sign /home/bill/tmp/myrsakey.pem -out /home/bill/tmp/sig -passin pass:a2479ff4cabb7677e192630ace9c02ff /home/bill/tmp/data
```
When it calls into ensure_key_loaded, pkey is NULL. The call from evp_md_init_internal passes NULL for pkey. I'm not sure if their is a better way to pickup the PKEY in the context blob or if this is a bug in OpenSSL. It seems to work if I call openssl genrsa and use that key blob.

```
Thread #1 [openssl] 153380 [core: 1] (Suspended : Signal : SIGSEGV:Segmentation fault)
        ensure_key_loaded() at tpm2-provider-signature.c:110 0x7ffff778fbe8
        rsa_signature_scheme_init() at tpm2-provider-signature.c:157 0x7ffff778fe1f
        tpm2_rsa_signature_digest_init() at tpm2-provider-signature.c:377 0x7ffff7790820
        do_sigver_init() at m_sigver.c:273 0x7ffff7c1acab
        EVP_DigestSignInit() at m_sigver.c:386 0x7ffff7c1b251
        evp_md_init_internal() at digest.c:145 0x7ffff7bebb3e
        EVP_DigestInit_ex() at digest.c:357 0x7ffff7bec4a8
        md_ctrl() at bio_md.c:146 0x7ffff7be311f
        BIO_ctrl() at bio_lib.c:579 0x7ffff7ad61af
        0x5555555af2fc
        <...more frames...>
```

**Comment by gotthardp** [comment]
Thanks for fixing this! The openssl tool does initialize a signing algorithm without any key and then frees it immediately, which is bit weird behaviour, but we should accept it. I just added a comment and few more NULL checks in 51f1e1244f62a47157ca26503d3f38368674e90b.
