### ISSUE TITLE
openssl-ca Unable to load CA certificate

### ISSUE THREAD

**Issue by mhummels** [tpm2-software/tpm2-openssl#37]
I try to use the TPM2 as secure storage for the private key of the intermediate CA. So I did the following steps to create a TPM2 key and get the handle:

```
tpm2_createprimary -G ecc256:ecdsa -g sha256 -C o -c prim.ctx -a 'fixedtpm|fixedparent|sensitivedataorigin|userwithauth|sign'
tpm2_evictcontrol -c prim.ctx
```

Then I created a CSR and signed that using the Root CA:
```
openssl req -new -sha256 -provider tpm2 -key handle:0x{HANDLE} -out intermediate-cert.csr
openssl req -in intermediate-cert.csr -text -noout -verify
openssl x509 -req -days 365 -in intermediate-cert.csr -CA device-root-cert.pem -CAkey device-root-key.pem -CAcreateserial -out intermediate-cert.pem -sha256
```

Now with the successfully signed intermediate CA, I tried to sign a given client certificate request:
`openssl ca -config ca.cnf -provider tpm2 -key handle:0x{HANDLE} -in device.csr -out device-cert.pem`

But this last step will not work in any configuration I tried so far. The current result is:
```
Using configuration from ca.cnf
Could not open file or uri for loading CA certificate from intermediate-cert.pem
40379991747F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file
40379991747F0000:error:1608010C:STORE routines:inner_loader_fetch:unsupported:../crypto/store/store_meth.c:359:No store loader found. For standard store loaders you need at least one of the default or base providers available. Did you forget to load them? Info: Global default library context, Scheme (file : 0), Properties (<null>)
Unable to load CA certificate
```
The intermediate-cert.pem is existing, so the error has to be something else. I also tried using the deprecated engine settings, but I did not get it running either. So please help to understand how to use private key stored in TPM for certificate signing as CA.

My installed versions are:
```
openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

tpm2 --version
tool="tpm2" version="5.2" tctis="libtss2-tctildr" tcti-default=tcti-device
```

Thank you.

**Comment by gotthardp** [comment]
Hello. The problem might be exactly what the error message said: *For standard store loaders you need at least one of the default or base providers available. Did you forget to load them?*

In other words: please try to add `-provider base` as well. It is needed to load files.

**Comment by mhummels** [comment]
Thank you for the quick response. That solved the problem. Maybe it would be helpful to add an example for CA usage, since I think it is a common use case to use the TPM module for storing the CA key.
