### ISSUE TITLE
Does CSR generation supports TPM authentication

### ISSUE THREAD

**Issue by danielcongxu** [tpm2-software/tpm2-openssl#40]
Hi,

I wonder if generating CSR using tpm2-openssl provides the capability as TPM key creation that an optional auth parameter could be specified while make the certification request? Specifically, like key auth or hierarchy auth?

The reason comes from that suppoes owner A and B boths works on a same machine, if A uses tpm2-openssl to manipulate a key (called key-A) to sign the CSR, the certificate generated from this CSR would be considered to only authrozie to user A but not B. user B shouldn't be allowed to manipulate key-A to generate its own CSR.

**Comment by gotthardp** [comment]
The key authorization is supported. One can specify the authorization via the `passin` argument. See for example https://github.com/tpm2-software/tpm2-openssl/blob/master/test/ec_createak_x509_csr_auth.sh.

**Comment by gotthardp** [comment]
And an C API example is now in https://github.com/tpm2-software/tpm2-openssl/blob/master/test/ec_genpkey_x509_csr.c
