### ISSUE TITLE
tpm2-openssl can't fully be integrated with OpenSSL 3 provider API

### ISSUE THREAD

**Issue by robret77** [tpm2-software/tpm2-openssl#42]
When a tool like kmodsign, which signs kernel modules for Secure Boot, is enhanced to support the provider API by adding calls to:

OSSL_PROVIDER_load(NULL, provider);
and
EVP_set_default_properties(NULL, propquery);

Then the tpm2-openssl support is limited, no handles or objects are supported. Instead of the typical db.key, I would like to use a noda TPM key (handle:0x81000103) for example:

```
$ sudo tpmkmodsign -P tpm2 -P default -Q "?provider=tpm2,tpm2.digest!=yes" sha256 handle:0x81000103 ./db.cer bridge.ko signed_bridge.ko
At main.c:264:
- SSL error:FFFFFFFF80000002:system library::No such file or directory: ../crypto/bio/bss_file.c:67
- SSL error:10000080:BIO routines::no such file: ../crypto/bio/bss_file.c:75
tpmkmodsign: handle:0x81000103: No such file or directory
```

This code runs well when a "db.key" is given instead of "handle:0x81000103", generated with tpm2-openssl like this:

```
$ sudo openssl genpkey -provider tpm2 -algorithm RSA -pkeyopt bits:2048 \
    -pkeyopt digest:sha256 -out db.key

$ sudo openssl req -provider tpm2 -provider default -key db.key -new -x509 -subj "/CN=Database Key/" \
    -out db.crt -days 3650 -sha256

$ sudo openssl x509 -in db.crt -out db.cer -outform DER

that would work now:

$ sudo tpmkmodsign -P tpm2 -P default -Q "?provider=tpm2,tpm2.digest!=yes" sha256 ./db.key ./db.cer bridge.ko signed_bridge.ko
```

**Comment by gotthardp** [comment]
The kmodsign tool may be using wrong openssl function for loading the key. I can have a look if you point me to the sources used to build your kmodsign.

**Comment by robret77** [comment]
I forked the latest Ubuntu 22.04 version of sbsigntool 0.9.4-2ubuntu2, renamed the kmodsign.c to tpmkmodsign.c and added this patch:

https://gist.github.com/robret77/f21a2b0d623f68765c55b9195d16f695

**Comment by gotthardp** [comment]
Yeah, the sbsigntool (in `fileio.c`) uses file operations: the `fileio_read_pkey` uses `BIO_new_file` and then `PEM_read_bio_PrivateKey`, which works for files only. If you want objects and handles you need to use the `OSSL_STORE_open` and `OSSL_STORE_INFO_get1_PKEY` instead, which will work for everything (files, objects, handles), maybe even in OpenSSL 1.1.1. A nice code snipplet was described here: https://github.com/tpm2-software/tpm2-openssl/issues/26#issuecomment-1057929799
