### ISSUE TITLE
Request for Release

### ISSUE THREAD

**Issue by hoinmic** [tpm2-software/tpm2-openssl#45]
Since I am relying on the functionality from commit 83cc5c20515f9b008b6dbce0b3a60c71744ee23a for a few embedded devices, I wanted to ask if a release could be made?

**Comment by gotthardp** [comment]
Yeah, it could and should be made. I will make one by the end of September.

**Comment by hoinmic** [comment]
Great, thank you.

**Comment by gotthardp** [comment]
I just made a release candidate `1.1.1-rc0`. You may want to double-check everything works for you.
If everything goes fine, the final release will be in 7 days.

**Comment by hoinmic** [comment]
Since I'm using Yocto, I've recreated the planned release with patches (starting from tpm2-openssl-1.1.0.tar.gz). Looks good for me.

**Comment by hoinmic** [comment]
I have additionally tested 1.1.1-rc0 locally. LGTM.

**Comment by gotthardp** [comment]
Done. Thanks for the tests.
https://github.com/tpm2-software/tpm2-openssl/releases/tag/1.1.1

**Comment by hoinmic** [comment]
thx
