### ISSUE TITLE
RSA sign/verify padding scheme

### ISSUE THREAD

**Issue by wxleong** [tpm2-software/tpm2-openssl#46]
In OpenSSL CLI,  RSA sign and verify padding scheme can be specified through `pad-mode:pss/pkcs1`. But this is not possible programmatically. In [tpm2-provider-types.c](https://github.com/tpm2-software/tpm2-openssl/blob/master/src/tpm2-provider-types.c#L79), only RSA_PKCS1_PSS_PADDING is available but not RSA_PKCS1_PADDING. Any reason why is this option disabled?

```
TPMI_ALG_RSA_SCHEME
tpm2_num_to_alg_rsa_scheme(const int num)
{
    switch (num)
    {
    case RSA_PKCS1_PSS_PADDING:
        return TPM2_ALG_RSAPSS;
+    case RSA_PKCS1_PADDING:
+        return TPM2_ALG_RSASSA;
    default:
        return TPM2_ALG_ERROR;
    }
}
```

**Comment by gotthardp** [comment]
Thanks for pointing this out.
I believe this is a bug. I cannot think of any reason why it should not be there.
