### ISSUE TITLE
Undeclared error when making on Raspberry PI 4

### ISSUE THREAD

**Issue by VVARELA15** [tpm2-software/tpm2-openssl#48]
I am installing on a raspberry pi 4 running Linux raspberrypi 5.15.76-v7l+. When I get to the ```make``` step I get an undeclared error. The screenshot of the error is shown below:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/11048844/200028105-0df0dd71-060a-435c-a0df-d73d5a307aa5.png">

**Comment by gotthardp** [comment]
That macro is defined in `include/openssl/core_names.h` since OpenSSL 3.0.0-beta1. I guess the build system found some wrong OpenSSL includes. Please double-check you have the right OpenSSL installed, including its header files.

**Comment by VVARELA15** [comment]
I see. This is the version I am running:
```
pi@raspberrypi:~/tpm2-openssl $ openssl version
OpenSSL 3.0.0-alpha17 20 May 2021 (Library: OpenSSL 3.0.0-alpha17 20 May 2021)
```

I will upgrade and see if that fixes it. Thank you.

**Comment by VVARELA15** [comment]
> That macro is defined in `include/openssl/core_names.h` since OpenSSL 3.0.0-beta1. I guess the build system found some wrong OpenSSL includes. Please double-check you have the right OpenSSL installed, including its header files.

I installed the main branch of openssl and now it works!

**Comment by VVARELA15** [comment]
Openssl version 3.2.0-dev solves this.
