### ISSUE TITLE
How to assign a persistent handle to a key stored in a file through the provider?

### ISSUE THREAD

**Issue by snambakam** [tpm2-software/tpm2-openssl#52]
I am trying to create a sub-key of a primary key (in the RH_OWNER hierarchy), using a C program. In order to do this, I believe, the handle of the primary key must be provided in the "parent" param when creating the sub-key. Is it possible to load a key persisted to a file and assign a persistent handle using the provider from a C program please? Is it possible for my service to take a compile time dependency only on OpenSSL and not directly on tpm2-tss? Or is it necessary to take a dependency on tpm2-tss APIs to do tpm2-evictcontrol and to manage nvram entries? Thanks.

**Comment by gotthardp** [comment]
> Is it possible to load a key persisted to a file and assign a persistent handle using the provider from a C program please?
No, I don't think the OpenSSL can save keys via a provider.

> Is it possible for my service to take a compile time dependency only on OpenSSL and not directly on tpm2-tss?
Providers are not a compile-time dependencies. Your service would depend on OpenSSL only that would dynamically load the tpm2 provider that depends on tpm2-tss.

> Or is it necessary to take a dependency on tpm2-tss APIs to do tpm2-evictcontrol and to manage nvram entries?
As said above, OpenSSL is unnable to save data to the NVRAM. You need to do this youself.
