### ISSUE TITLE
Many operations failing with TPM error 0x902

### ISSUE THREAD

**Issue by nickrbogdanov** [tpm2-software/tpm2-openssl#58]
I have an Intel NUC 11 running Ubuntu 22.04 and kernel 5.15.0-60-generic.  I have been trying to experiment with running a TLS server using the TPM to hold the server's private key.  My first attempt involved installing the `tpm2-openssl` package shipped with Ubuntu, v1.0.1.  I was able to successfully generate keys on the TPM by doing:

```
tpm2_createprimary -C o -g sha256 -G ecc -c primary_sh.ctx
tpm2_evictcontrol -C o -c primary_sh.ctx 0x81000001
openssl genpkey -provider tpm2 -algorithm EC -pkeyopt group:P-256 -pkeyopt parent:0x81000001 -out eckey.pem
openssl pkey -provider tpm2 -provider base -in eckey.pem -pubout -out eckey.pub.pem
```

So this TPM isn't completely broken.  However, every time I tried to start up a TLS `s_server` with OpenSSL, I got an 0x902 (out of memory for object contexts) error.  e.g.

```
openssl s_server -provider tpm2 -provider default -propquery '?provider=tpm2' -www -accept 443 -cert /etc/nginx/certs/server-current.pem -key handle:0x81000002
```

`tpm2_getcap handles-transient` shows no output.  `tpm2_getcap handles-persistent` (executed before the tests) just shows the keys I stored myself.  `tpm2_flushcontext -t` (or with `-l` or `-s`) doesn't help.

I then uninstalled the Ubuntu `tpm2-openssl` package and built the latest tpm2-openssl package from source.  Running `make check`, I see similar results from the known-good tests in the suite:

```
PASS: test/list.sh
PASS: test/rand.sh
FAIL: test/rsa_genrsa_check.sh
FAIL: test/rsa_genpkey_sign.sh
FAIL: test/rsa_genpkey_sign_rawin.sh
FAIL: test/rsa_genpkey_auth_parent.sh
PASS: test/rsa_createak_auth.sh
PASS: test/rsa_createak_sign_object.sh
PASS: test/rsa_createak_sign_handle.sh
PASS: test/rsa_create_decrypt.sh
PASS: test/rsa_genpkey_x509_cert.sh
FAIL: test/rsa_genpkey_x509_cmp.sh
PASS: test/rsa_genpkey_x509_cms.sh
FAIL: test/rsa_genpkey_tls_server.sh
PASS: test/rsa_createak_x509_csr.sh
FAIL: test/rsapss_genpkey_sign_rawin.sh
FAIL: test/rsapss_createak_tls_server.sh
FAIL: test/rsa_pki/rsa_pki.sh
PASS: test/ec_genpkey_check.sh
PASS: test/ec_genpkey_parameters.sh
PASS: test/ecdsa_genpkey_auth.sh
PASS: test/ecdsa_genpkey_sign_rawin.sh
PASS: test/ecdsa_createak_sign_handle.sh
PASS: test/ecdh_genpkey_keyexch.sh
PASS: test/ecdh_create_keyexch_index.sh
PASS: test/ec_createak_x509_csr.sh
PASS: test/ec_createak_x509_cms.sh
PASS: test/ec_createak_x509_index.sh
FAIL: test/ec_genpkey_tls_server.sh
FAIL: test/ec_pki/ec_pki.sh
PASS: test/store_x509_index.sh
PASS: test/store_errors.sh
PASS: test/digest.sh
PASS: test/cipher_aes128_ecb.sh
PASS: test/cipher_aes128_cbc.sh
PASS: test/cipher_aes256.sh
PASS: test/cipher_aes256_nopad.sh
SKIP: test/cipher_camellia128.sh
PASS: test/selftest
```

```
$ grep "Esys Finish ErrorCode" test/*.log
test/ec_genpkey_tls_server.log:ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902)
test/rsa_genpkey_auth_parent.log:ERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x000002c4)
test/rsa_genpkey_sign.log:ERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x000002c4)
test/rsa_genpkey_sign_rawin.log:ERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x000002c4)
test/rsa_genpkey_tls_server.log:ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902)
test/rsa_genpkey_x509_cmp.log:ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902)
test/rsa_genrsa_check.log:ERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x000002c4)
test/rsapss_createak_tls_server.log:ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902)
test/rsapss_genpkey_sign_rawin.log:ERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x000002c4)
test/store_errors.log:ERROR:esys:src/tss2-esys/api/Esys_ReadPublic.c:104:Esys_ReadPublic() Esys Finish ErrorCode (0x00000184)
```

This happens whether I use `/dev/tpm0` or `/dev/tpmrm0`.  I am not running tpm2-abrmd and there is nothing else in `ps` mentioning tpm, except the kernel's `[tpm_dev_wq]`.

I have physically powered the machine off + on, no change.

What might be going wrong here?

**Comment by gotthardp** [comment]
Hello. This is likely because you are not running the `tpm2-abrmd`. Running the `tpm2-abrmd` is necessary for the complex operations such as SSL and X.509 operations, see also https://github.com/tpm2-software/tpm2-openssl#limited-resources

This is because OpenSSL very "context greedy" and the complex operations require more contexts than available in the TPM chip.

**Comment by nickrbogdanov** [comment]
Thanks, that worked.  FTR the required packages on Ubuntu were:

```
apt install tpm2-openssl tpm2-tools tpm2-abrmd libtss2-tcti-tabrmd0
```

Absent the latter package, the OpenSSL CLI tests would still try to use the in-kernel resource manager, and most would fail.

In my research I did see insinuations [here](https://dev.to/nandhithakamal/how-to-tpm-part-2-55ao) and [here](https://wiki.archlinux.org/title/Trusted_Platform_Module) that the in-kernel RM is intended to fully replace tpm2-abrmd.  Perhaps the in-kernel RM is sufficient for extremely simple use cases, but if it can't even handle `openssl s_server` and the other unit tests in this repo, it might be worth adding a note to the README to indicate that tpm2-abrmd is essentially mandatory and link to instructions on setting it up.

**Comment by gotthardp** [comment]
Thanks for the suggestions. I made a commit f40309468e14d4d4437a2b481e267035463ba326 with some changes to the README and INSTALL instructions.

The internet resources are not always right. The in-kernel RM is designed for a single command at once. The OpenSSL however often runs several commands in parallel. We had an interesting conversation on this some years ago:
https://lists.linuxfoundation.org/pipermail/tpm2/2021-October/002474.html

**Comment by nickrbogdanov** [comment]
> Why are we doing hashing with the TPM? If we're in an OpenSSL provider cant we just use software provided hashing routines? I see hashing is configurable, but I would imagine off be default is what you want.

Stepping back a bit -- for the simple case of storing TLS server keys on the TPM, does the Provider interface offer a way to selectively offload the appropriate steps of the TLS handshake onto the TPM and then do the rest in software?

I'm running a number of web servers that store the TLS private server key in a Yubikey PIV slot, and access it via PKCS#11 through the old ENGINE interface.  So in my nginx configuration I specify `ssl_engine pkcs11` and then `ssl_certificate_key "engine:pkcs11:pkcs11:manufacturer=piv_II;id=%01;pin-value=123456"` corresponding to the x.509 certificate.  This tells OpenSSL to ask the Yubikey to perform signing operations with the private key during the TLS handshake, and then to perform all of the other steps in software.

I understand from the thread that there are other situations where you really need the TPM to be performing the hash itself, but for TLS I'd want to offload the bare minimum onto the TPM.  Both for latency reasons and to optimize resource management.

Performance-wise, the PKCS#11 Yubikey setup only adds about 90ms to the initial handshake with ECC.  It's barely noticeable in low-traffic scenarios.  By contrast I noticed that `test/ec_genpkey_tls_server.sh` takes a couple of seconds to run with a hardware TPM.

**Comment by gotthardp** [comment]
Alright. Let me see if I can disable the digest and still have all tests passed.

**Comment by gotthardp** [comment]
Done. In the latest `master` I disabled the unnecessary symmetric ciphers and updated the tests to pass even then. i would be interested to know how much faster is your TLS handshake now.

**Comment by gotthardp** [comment]
Answered and fixed by 8d3f08b2ca6b7faf93692d8e2873c86db57e7b6c.

**Comment by nickrbogdanov** [comment]
Initial results look good.

Running `time curl -k https://localhost/` with the old code (digests going through TPM) I saw it taking over 5 seconds for a single HTTP request:

```
real	0m5.665s
user	0m0.052s
sys	0m0.017s
```

With 1.2.0-rc0 it's a massive improvement:

```
real	0m0.083s
user	0m0.010s
sys	0m0.003s
```

Compared with using pure software ECC:

```
openssl ecparam -name prime256v1 -genkey -noout -out ecc_private.pem
openssl pkey -in ecc_private.pem -pubout -out ecc_public.pem
openssl req -x509 -subj "/C=GB/CN=foo" -key ecc_private.pem -out cert_sw.pem
openssl s_server -www -accept 443 -cert cert_sw.pem -key ecc_private.pem
```

```
real	0m0.012s
user	0m0.008s
sys	0m0.004s
```

Now running time `bash -c 'for x in {1..100}; do curl -k https://localhost/; done'` I see:

`s_server` using software ECC:

```
real	0m0.515s
user	0m0.341s
sys	0m0.123s
```

`s_server` using TPM2:

```
real	0m6.775s
user	0m1.125s
sys	0m0.479s
```

so there is a lag (as expected), but I'd assume that in practice it will be largely mitigated by TLS session reuse.

The above tests were conducted with `tpm2-abrmd` running in the background.  If I uninstall `tpm2-abrmd` the test still passes, with a significant performance hit:

```
real	0m21.991s
user	0m0.789s
sys	0m0.567s
```

My next step is to patch nginx so (ideally) there would be an easy way to enable tpm2-openssl "out of the box": https://trac.nginx.org/nginx/ticket/2449#ticket

I guess I'll need to find a way to pass in the `propquery` string to tell OpenSSL to prefer TPM2 for operations that are implemented in both the tpm2 provider and the default provider?  Or is there a better way to make this the default?

**Comment by gotthardp** [comment]
With the hashes disabled there is (hopefully) no need to specify any propquery. All you (should) need is loading the tpm2 **and** the default provider.
