### ISSUE TITLE
Heap exception if signing rsa key in tpm2_signature_get_ctx_params on windows

### ISSUE THREAD

**Issue by philippun1** [tpm2-software/tpm2-openssl#70]
Hi,
I'm currently trying to create a rsa key pair and sign it with `X509_sign`. The key pair creation works (with `EVP_RSA_gen`), but I get a heap exception in `tpm2_signature_get_ctx_params`.

The tpm2-openssl provider and tpm2-tss is built with clang, OpenSSL is built with msvc. I tried several combinations (VS 2017, 2019, 2022) with the clang versions of each VS version. The error is happening every time:

`HEAP[tpm-test.exe]: Invalid address specified to RtlValidateHeap( 000001DAEC2F0000, 000001DAEC33EBA0 )`

The error is happening when `free(aid);` is being called in tpm2-openssl, `aid` itself is being allocated in OpenSSL. So I would assume the problem might be due to allocation in a msvc library and freeing in a clang library?

I have tried OpenSSL 3.0 and 3.1 with tpm2-openssl 1.2.0-rc0.

This is the command line output:
```
PROVIDER INIT
Loaded tpm2 provider
RSA GEN INIT rsa 3
RSA GEN_SET_PARAMS [ bits ]
RSA GEN 2048 bits
RSA GEN parent: primary 0x40000001
RSA GET_PARAMS [ bits security-bits max-size ]
RSA CLEANUP
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER rsa pkcs1/der DOES_SELECTION 0x86
ENCODER rsa pkcs1/pem DOES_SELECTION 0x86
ENCODER rsa SubjectPublicKeyInfo/der DOES_SELECTION 0x86
ENCODER rsa SubjectPublicKeyInfo/pem DOES_SELECTION 0x86
ENCODER rsa SubjectPublicKeyInfo/der ENCODE 0x86
SIGN DIGEST_INIT rsa MD=SHA256
SIGN GET_CTX_PARAMS [ algorithm-id ]
```

Is there anyway to get this working? Compiling tpm2-openssl with msvc is not possible without further ado, because it does not support variable array length. And I found no way to compile OpenSSL with clang.

**Comment by gotthardp** [comment]
It is worth checking if this is the reason. I pushed a possible fix to the `master` branch. Could you please check whether it helps?
