### ISSUE TITLE
tpm2 as default provider, RAND_status  returns False

### ISSUE THREAD

**Issue by mccarey** [tpm2-software/tpm2-openssl#87]
Hello,

I  am trying the tpm2  provider. And what i observe is that when it is the default provider the function RAND_status  returns systematically false. 
I don't know if this is the right behavior, that's why i am here to ask.

Thanks

**Comment by gotthardp** [comment]
True. That's a bug-- thanks for reporting this. The latest `master` branch should work as expected.
