### ISSUE TITLE
Out-of-bound write

### ISSUE THREAD

**Issue by tanstafel** [tpm2-software/tpm2-openssl#90]
This looks like an out of bound write in case `i == j == count` because only `count` algorithms are allocated:
https://github.com/tpm2-software/tpm2-openssl/blob/de9ed8e32901d5d6554a9042142f4a59629815e1/src/tpm2-provider.c#L82

**Comment by gotthardp** [comment]
Not really. This is just a filtering and every list processed by the `tpm2_operation` has a NULL item at the end. The `for` in fact always finishes when `algs[i].algs == NULL` and never when `i == count`. But I agree it may be confusing.

**Comment by tanstafel** [comment]
Ok, I see. The variable `count` is misleading then because it does not contain the algorithm count but the number of entries in `algs` which includes the sentinel which is not an actual algorithm.

**Comment by gotthardp** [comment]
True. I made a little improvement: https://github.com/tpm2-software/tpm2-openssl/commit/8f1a285c89e92b4b9e96c916e86cbafd99799c12
