### ISSUE TITLE
Can't seem to use `-pkeyopt parent` with openssl 3 `genpkey` using RSA

### ISSUE THREAD

**Issue by aoswald** [tpm2-software/tpm2-openssl#95]
I'm attempting to integrate the `tpm2-pkcs11` engine by [linking](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/INTEROPERABILITY.md) an _existing_ TSS2 PRIVATE KEY.  The `tpm2_ptool` `init` command creates a primary key in the owner hierarchy that needs to be the parent; for sake of discussion here, let's say it's at handle `0x81000001`.

Initial attempts were using Ubuntu packages, but I'm also getting the error when `tpm2-openssl` is built from scratch.

Pertinent environment values:
- Ubuntu 22.04 Server
- openssl version: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

The openssl genpkey command:
`openssl genpkey -provider tpm2 -algorithm RSA -pkeyopt parent:0x81000001 -out testkey.priv`

And the `--enable-debug=yes` configure output:
```
PROVIDER INIT
genpkey: Error setting parent:0x81000001 parameter:
PROVIDER TEARDOWN
```

Any advice on what I seem to be doing incorrectly?

thanks in advance!
-ao

**Comment by gotthardp** [comment]
You should be able to use that. It works for me and there is even a test for this: https://github.com/tpm2-software/tpm2-openssl/blob/master/test/rsa_genpkey_auth_parent.sh

I am not able to reproduce this not even on a clean Ubuntu 22.04. Could you please prepare a test `.sh` script that fails on a clean Ubuntu, so I can test it?

**Comment by aoswald** [comment]
While I get that situated, yes, I ran the tests by way of `make check` and the majority of them fail.

What _did_ work, however, was using RSA-PSS.

```
$ make check
make  test/selftest test/ec_genpkey_store_load test/rsa_genpkey_decrypt
make[1]: Entering directory '/tmp/tpm2-openssl'
make[1]: 'test/selftest' is up to date.
make[1]: 'test/ec_genpkey_store_load' is up to date.
make[1]: 'test/rsa_genpkey_decrypt' is up to date.
make[1]: Leaving directory '/tmp/tpm2-openssl'
make  check-TESTS
make[1]: Entering directory '/tmp/tpm2-openssl'
make[2]: Entering directory '/tmp/tpm2-openssl'
PASS: test/list.sh
PASS: test/rand.sh
FAIL: test/rsa_genrsa_check.sh
FAIL: test/rsa_genpkey_sign.sh
FAIL: test/rsa_genpkey_sign_rawin.sh
FAIL: test/rsa_genpkey_auth_parent.sh
FAIL: test/rsa_createak_auth.sh
FAIL: test/rsa_createak_sign_object.sh
FAIL: test/rsa_createak_sign_handle.sh
FAIL: test/rsa_create_decrypt_pkcs1.sh
FAIL: test/rsa_create_decrypt_oaep.sh
FAIL: test/rsa_genpkey_x509_cert.sh
FAIL: test/rsa_genpkey_x509_cmp.sh
FAIL: test/rsa_genpkey_x509_cms.sh
FAIL: test/rsa_genpkey_tls_server.sh
FAIL: test/rsa_createak_x509_csr.sh
PASS: test/rsapss_genpkey_sign_rawin.sh
PASS: test/rsapss_createak_tls_server.sh
FAIL: test/rsa_pki/rsa_pki.sh
FAIL: test/ec_genpkey_check.sh
FAIL: test/ec_genpkey_parameters.sh
FAIL: test/ec_genpkey_x509_cms.sh
FAIL: test/ecdsa_genpkey_sign_auth.sh
FAIL: test/ecdsa_genpkey_sign_rawin.sh
FAIL: test/ecdsa_createak_sign_handle.sh
FAIL: test/ecdh_genpkey_keyexch.sh
FAIL: test/ecdh_create_keyexch_index.sh
FAIL: test/ec_createak_x509_cert.sh
FAIL: test/ec_createak_x509_csr_auth.sh
FAIL: test/ec_createak_x509_cms.sh
FAIL: test/ec_createak_x509_index.sh
FAIL: test/ec_genpkey_tls_server.sh
FAIL: test/ec_pki/ec_pki.sh
PASS: test/store_x509_index.sh
PASS: test/store_errors.sh
PASS: test/selftest
PASS: test/ec_genpkey_store_load
PASS: test/rsa_genpkey_decrypt
============================================================================
Testsuite summary for tpm2-openssl 1.2.0-9-g0d5b0d7
============================================================================
# TOTAL: 38
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  29
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/tpm2-software/tpm2-openssl/issues
============================================================================
make[2]: *** [Makefile:1190: test-suite.log] Error 1
make[2]: Leaving directory '/tmp/tpm2-openssl'
make[1]: *** [Makefile:1298: check-TESTS] Error 2
make[1]: Leaving directory '/tmp/tpm2-openssl'
make: *** [Makefile:1524: check-am] Error 2
```

Any idea from that output?

**Comment by gotthardp** [comment]
Please attach also the `./test-suite.log` generated by the test suite. That might explain the reasons.

**Comment by aoswald** [comment]
> Please attach also the ./test-suite.log generated by the test suite. That might explain the reasons.
[test-suite.log](https://github.com/tpm2-software/tpm2-openssl/files/13282141/test-suite.log)

**Comment by aoswald** [comment]
I just created a primary on my own (instead of letting `tpm2-pkcs11`'s `tpm2_ptool init` take care of it and things appear to be working.  I _did_ add the `-propquery '?provider=tpm2'` though.  Let me do a clean run of everything again just to be certain.

And thanks so very much for the prompt attention on this, @gotthardp !

**Comment by gotthardp** [comment]
Cool. Out of curiosity: in your `/etc/ssl/openssl.cnf` (or the openssl config you were using), is there something enabled in your `[provider_sect]`? If there *is* something, that would explain the need for the extra `-propquery '?provider=tpm2'`.

**Comment by aoswald** [comment]
Not much there:
```
# List of providers to load
[provider_sect]
default = default_sect
```

**Comment by gotthardp** [comment]
Thanks. That's important, actually. That line enables the `default` provider, so one has to **always** provide the `-propquery '?provider=tpm2'` to avoid conflict with the `tpm2` provider. I will document it.

**Comment by aoswald** [comment]
I believe I've identified where things get fouled up: updating `/etc/ssl/openssl.cnf` to configure the `tpm2-pkcs11` module.  I've added the `engines = engines_section` and subsequent links/sections.

```
[openssl_init]
providers = provider_sect
ssl_conf = ssl_sect
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
MODULE_PATH = /usr/lib/x86_64-linux-gnu/pkcs11/libtpm2_pkcs11.so
init=0
```
Is there anything glaring there that would cause the `genpkey: Error setting ...` issues?

thanks!

**Comment by gotthardp** [comment]
I added a new section to the documentation that might clarify that a bit: https://github.com/tpm2-software/tpm2-openssl/blob/master/docs/initialization.md#openssl-configuration-file

Have a look in the `provider_sect` in your `openssl.cnf`: I bet the default provider will be activated (loaded by default).

When the default provider is enabled, the
```
openssl genpkey -provider tpm2 -algorithm RSA -pkeyopt parent:0x81000001 -out testkey.priv
```
becomes equivalent to
```
openssl genpkey -provider default -provider tpm2 -algorithm RSA -pkeyopt parent:0x81000001 -out testkey.priv
```
and since no `-propquery` is defined, the first (`default`) provider is loaded and this doesn't recognize the `parent` opt.

The `openssl.cnf` with distro-provided default content is a source of weird situations, because it changes the `openssl` command behaviour without any warning.

**Comment by aoswald** [comment]
> Have a look in the provider_sect in your openssl.cnf: I bet the default provider is activated (loaded by default).
Here's what I've got
```
[provider_sect]
default = default_sect
# The fips section name should match the section name inside the
# included fipsmodule.cnf.
# fips = fips_sect

# If no providers are activated explicitly, the default one is activated implicitly.
# See man 7 OSSL_PROVIDER-default for more details.
#
# If you add a section explicitly activating any other provider(s), you most
# probably need to explicitly activate the default provider, otherwise it
# becomes unavailable in openssl.  As a consequence applications depending on
# OpenSSL may not work correctly which could lead to significant system
# problems including inability to remotely access the system.
[default_sect]
# activate = 1
```

Did you possibly read my prior comment too quickly?  **All** problems are resolved when the **engine** configuration is commented out.  I should probably follow up with the tpm2-pkcs11 folks to mention that their [documentation for integrating with openssl](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/OPENSSL.md) causes these issues (or it least they did for me on Ubuntu 22.04 using the `libengine-pkcs11-openssl` package).  For what it's worth, the openssl configuration enhancements _were_ in fact required when utilizing a YubiKey for PIV.

**Comment by aoswald** [comment]
I'm happy to answer any other questions or try other tests, but am also in agreement this can be closed if that's also your opinion, @gotthardp .  And thanks again for all the very timely responses!  :smiley:

**Comment by gotthardp** [comment]
All clear now, thanks. I saw the issues were resolved, but I wanted to investigate a bit more whether it was only the engine configuration, or also the provider configuration. It was just the engine. All providers were disabled in the openssl.cnf.
