### ISSUE TITLE
openssl cmp support with keys inside the tpm using tpm handles to send IR

### ISSUE THREAD

**Issue by sumanth797** [tpm2-software/tpm2-openssl#98]
Hi,

[https://github.com/tpm2-software/tpm2-openssl/blob/master/test/ec_genpkey_store_load.c](https://github.com/tpm2-software/tpm2-openssl/blob/master/test/ec_genpkey_store_load.c)

I'm using above link as the reference for testing the cmp using openssl cmp commands.
Do we have any example for sending IR using the keys present in the tpm handle like handle:0x81010002?pass with authentication .

For example,
I'm trying to create client key and certificate, signed by the root CA from the above example link,

> openssl req -provider-path /usr/lib64/ossl-packages/ -provider tpm2 -provider default -propquery '?provider=tpm2' -x509 -key handle:0x81010002?pass -passin pass:Aw2WLz9bHAideywh -sha256 -nodes -config /config/csr.cnf  -keyout test-ca-key.pem -out test-ca-cert.pem
> 
> openssl req -provider-path /usr/lib64/ossl-packages/ -provider tpm2 -provider default -propquery '?provider=tpm2' -x509 -sha256 -nodes -config /config/csr.cnf -CAkey handle:0x81010002?pass -passin pass:Aw2WLz9bHAideywh -CA test-ca-cert.pem -key test-server-key.pem -out test-server-cert.pem

**These quoted commands are working**, but the **below command is failing**

**failed command:**

openssl req -provider-path /usr/lib64/ossl-packages/ -provider tpm2 -provider default -propquery '?provider=tpm2' -x509 -sha256 -nodes -config /config/csr.cnf  -CAkey handle:0x81010002?pass -passin pass:Aw2WLz9bHAideywh -CA test-ca-cert.pem -keyout test-client-key.pem -out test-client-cert.pem

**And it throws error,**
PROVIDER INIT
DIGEST SHA1 GET_PARAMS [ blocksize size xof algid-absent ]
DIGEST SHA256 GET_PARAMS [ blocksize size xof algid-absent ]
DIGEST SHA384 GET_PARAMS [ blocksize size xof algid-absent ]
RSA GEN INIT rsa 3
RSA GEN_SET_PARAMS [ bits ]
RAND NEW
RAND GET_CTX_PARAMS [ state ]
Warning: generating random key material may take a long time
if the system has a poor entropy source
RSA GEN 2048 bits
RSA GEN parent: primary 0x40000001
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2)
RSA FREE
req: Error generating RSA key
4061B942C67F0000:error:40000002:tpm2:tpm2_build_primary:authorization failure:src/tpm2-provider-pkey.c:316:
RAND FREE

**Can you help us here by sharing the reference incase if the keys are stored in the tpm for using them during cmp IR.
Is there such support provided?**

**Comment by Tyrrx** [comment]
I enabled the default and tpm2 provider via the [OSSL configuration file](https://github.com/tpm2-software/tpm2-openssl/blob/master/docs/initialization.md#openssl-configuration-file). You should also be able to use the providers by appending the following to the command below: `-provider default -provider tpm2`

Here is a config I used that worked for me. You need to change your values accordingly and create a new private key first.
```cnf
#workflow.cnf:
[ra]
server = cmp-endpoint.example:443

[imprint]
cmd = ir

#your endpoint path:
path = .well-known/cmp/initialization/ldevidgenericcert/default

own_trusted = store/trusted/vendor/vendor_root_ca.crt, store/trusted/vendor/vendor_intermediate_ca.crt
cert = store/own/idevid/my_device.crt
key = handle:0x81010002
#keypass = pass:xxxx

tls_cert = $cert
tls_key = $key
#tls_keypass = $keypass

# all certs to trust the domain go in here:
trusted = store/trusted/domain/ldevid-chain.pem
# all certs to trust the cmp server go in here:
tls_trusted = store/trusted/infrastructure/infrastructure_root_ca.cer, store/trusted/infrastructure/infrastructure_intermediate_ca.cer

# assume you have generated a new key first:
newkey = handle:0x81010003
#newkeypass = $keypass

reqexts = empty
policies = empty
certout = store/own/ldevid_generic/my_device.pem
cacertsout = store/trusted/domain/ldevid_generic_ca_chain.pem

[empty]

```

Run it with:
```sh
openssl cmp -config workflow.cnf -section ra,imprint
```

**Comment by sumanth797** [comment]
Hi @Tyrrx , Thanks for the reply. 

- I'm running this command for IR by using the **client authentication option** as **extracerts** and it is failing due to,
 **CMP error: missing trust anchor
 CMP error: error validating protection**


 openssl cmp -provider-path /usr/lib64/ossl-packages/ -provider tpm2 -provider default -propquery '?provider=tpm2,tpm2.digest!=yes' -cmd ir -server 10.41.111.231:8081/pkix/ -recipient "/C=IN/O=CI/CN=SubCA" -key handle:0x81010002?pass -keypass pass:ynM67sdZjEJesWk6 -cert vendorcert.pem **-extracerts** rootCA.pem,factory.pem -newkey handle:0x81010004?pass -newkeypass pass:ynM67sdZjEJesWk6  -subject "/C=IN/O=CI/CN=SubEE" -certout test-my-cert1.pem -cacertsout test-my-ca1.pem -verbosity 8
 
cmp_main:apps/cmp.c:2833:CMP info: using section(s) 'cmp' of OpenSSL configuration file '/etc/pki/tls/openssl.cnf'
cmp_main:apps/cmp.c:2842:CMP info: no [cmp] section found in config file '/etc/pki/tls/openssl.cnf'; will thus use just [default] and unnamed section if present
PROVIDER INIT
DIGEST SHA1 GET_PARAMS [ blocksize size xof algid-absent ]
DIGEST SHA256 GET_PARAMS [ blocksize size xof algid-absent ]
DIGEST SHA384 GET_PARAMS [ blocksize size xof algid-absent ]
STORE/OBJECT OPEN handle:0x81010002?pass
STORE/OBJECT SET_PARAMS [ properties ]
STORE/OBJECT SET_PARAMS [ expect ]
STORE/OBJECT LOAD
STORE/OBJECT LOAD pkey
STORE/OBJECT LOAD found RSA
RSA LOAD
RSA GET_PARAMS [ bits security-bits max-size ]
RSA HAS 1
STORE/OBJECT CLOSE
**setup_protection_ctx:apps/cmp.c:1448:CMP warning: will not authenticate server due to missing -secret, -trusted, or -srvcert**
DER DECODER DECODE
CMP DEBUG: trying to build chain for own CMP signer cert
CMP DEBUG: success building chain for own CMP signer cert
DER DECODER DECODE
DER DECODER DECODE
STORE/OBJECT OPEN handle:0x81010004?pass
STORE/OBJECT SET_PARAMS [ properties ]
STORE/OBJECT SET_PARAMS [ expect ]
STORE/OBJECT LOAD
STORE/OBJECT LOAD pkey
STORE/OBJECT LOAD found RSA
RSA LOAD
RSA GET_PARAMS [ bits security-bits max-size ]
RSA HAS 1
STORE/OBJECT CLOSE
setup_client_ctx:apps/cmp.c:2009:CMP info: will contact http://10.41.111.231:8081/pkix/
RAND NEW
RAND NEW
RAND GET_CTX_PARAMS [ max_request ]
RAND GENERATE
CMP DEBUG: Starting new transaction with ID=9C:18:57:FA:6D:06:21:8B:19:C2:7F:93:D7:05:93:33
RAND GET_CTX_PARAMS [ max_request ]
RAND GENERATE
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/der DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER tss PrivateKeyInfo/pem DOES_SELECTION 0x86
ENCODER rsa pkcs1/der DOES_SELECTION 0x86
ENCODER rsa pkcs1/pem DOES_SELECTION 0x86
ENCODER rsa SubjectPublicKeyInfo/der DOES_SELECTION 0x86
ENCODER rsa SubjectPublicKeyInfo/pem DOES_SELECTION 0x86
ENCODER rsa SubjectPublicKeyInfo/der ENCODE 0x86
RSA GET_PARAMS [ default-digest mandatory-digest ]
SIGN DIGEST_INIT rsa MD=SHA2-256
SIGN GET_CTX_PARAMS [ algorithm-id ]
SIGN DIGEST_SIGN estimate
SIGN DIGEST_SIGN
RSA HAS 2
RSA NEW
RSA IMPORT [ n e ]
RSA MATCH 0x6
SIGN DIGEST_INIT rsa MD=SHA256
SIGN GET_CTX_PARAMS [ algorithm-id ]
SIGN DIGEST_SIGN estimate
SIGN DIGEST_SIGN
CMP info: sending IR
CMP DEBUG: connecting to CMP server 10.41.111.231:8081
CMP DEBUG: finished reading response from CMP server
CMP info: received IP
DIGEST NEW
DIGEST INIT
DIGEST UPDATE
DIGEST FINAL
DIGEST FREE
DIGEST NEW
DIGEST INIT
DIGEST UPDATE
DIGEST FINAL
DIGEST FREE
DIGEST NEW
DIGEST INIT
DIGEST UPDATE
DIGEST FINAL
DIGEST FREE
CMP DEBUG: validating CMP message
**CMP info: no trust store nor pinned server cert available for verifying signature-based CMP message protection
CMP error: missing trust anchor
CMP error: error validating protection**
CMP DEBUG: disconnected from CMP server
RSA FREE
RSA FREE
RSA FREE
RAND FREE
RAND FREE
PROVIDER TEARDOWN

-  **But using the client authentication option as -secret and -ref  it is writing out the cert and cacert.**
openssl cmp -provider-path /usr/lib64/ossl-packages/ -provider tpm2 -provider default -propquery '?provider=tpm2,tpm2.digest!=yes' -cmd ir -server 10.41.111.231:8081/pkix/ -recipient "/C=IN/O=CI/CN=SubCA" -key handle:0x81010002?pass -keypass pass:ynM67sdZjEJesWk6 -cert vendorcert.pem -ref 1234 -secret pass:AB-CD3E-FgHI-JkLM -newkey handle:0x81010004?pass -newkeypass pass:ynM67sdZjEJesWk6  -subject "/C=IN/O=CI/CN=SubEE" -certout test-my-cert1.pem -cacertsout test-my-ca1.pem -verbosity 8

**Can you help us here what needs to be done when **extracerts** option is used for client authentication?**
**Is there any way i can achieve it using the extracerts option?**

**Comment by sumanth797** [comment]
Hi,
How to use the **extracerts** output as a **trust anchor** to validate the **IR request?** Is that possible?
